import { Client, type ClientProps, type RegistrationStatus } from '../../domain/client.entity';
import type { ClientStatus } from '@nexus/types';
import type { clients } from '../../../../database/schema';

type ClientSelectRow = typeof clients.$inferSelect;

export class ClientMapper {
  static toDomain(row: ClientSelectRow): Client {
    const props: ClientProps = {
      id: row.id,
      companyName: row.companyName,
      cnpj: row.cnpj,
      cnpjRoot: row.cnpjRoot,
      tradeName: row.tradeName,
      segmentId: row.segmentId,
      phone: row.phone,
      email: row.email,
      addressStreet: row.addressStreet,
      addressNumber: row.addressNumber,
      addressComplement: row.addressComplement,
      addressNeighborhood: row.addressNeighborhood,
      addressCity: row.addressCity,
      addressState: row.addressState,
      addressZip: row.addressZip,
      creditProductId: row.creditProductId,
      requestedAmount: row.requestedAmount,
      approvedAmount: row.approvedAmount,
      hasGuarantees: row.hasGuarantees ?? false,
      isJudicialRecovery: row.isJudicialRecovery ?? false,
      workingCapitalNotes: row.workingCapitalNotes,
      status: row.status as ClientStatus,
      registrationStatus: (row.registrationStatus ?? 'prospect') as RegistrationStatus,
      stateRegistration: row.stateRegistration,
      cityRegistration: row.cityRegistration,
      foundedAt: row.foundedAt,
      establishedAt: row.establishedAt,
      closedAt: row.closedAt,
      closureReason: row.closureReason,
      isPep: row.isPep ?? false,
      isPepRelated: row.isPepRelated ?? false,
      isOfacListed: row.isOfacListed ?? false,
      hasRiskProfession: row.hasRiskProfession ?? false,
      hasRiskActivity: row.hasRiskActivity ?? false,
      hasRiskCity: row.hasRiskCity ?? false,
      riskRating: row.riskRating,
      revenueSituation: row.revenueSituation,
      economicGroupId: row.economicGroupId,
      legacySgsId: row.legacySgsId,
      legacyNfId: row.legacyNfId,
      assignedTo: row.assignedTo,
      teamId: row.teamId,
      regionId: row.regionId,
      cnpjStatus: row.cnpjStatus,
      cnpjValidatedAt: row.cnpjValidatedAt,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
      submittedAt: row.submittedAt,
      approvedAt: row.approvedAt,
      homologatedAt: row.homologatedAt,
    };
    return Client.reconstitute(props);
  }

  static toPersistence(client: Client): Record<string, unknown> {
    return {
      companyName: client.companyName,
      cnpj: client.cnpj,
      cnpjRoot: client.cnpjRoot,
      tradeName: client.tradeName,
      segmentId: client.segmentId,
      phone: client.phone,
      email: client.email,
      addressStreet: client.addressStreet,
      addressNumber: client.addressNumber,
      addressComplement: client.addressComplement,
      addressNeighborhood: client.addressNeighborhood,
      addressCity: client.addressCity,
      addressState: client.addressState,
      addressZip: client.addressZip,
      creditProductId: client.creditProductId,
      requestedAmount: client.requestedAmount,
      approvedAmount: client.approvedAmount,
      hasGuarantees: client.hasGuarantees,
      isJudicialRecovery: client.isJudicialRecovery,
      workingCapitalNotes: client.workingCapitalNotes,
      status: client.status,
      registrationStatus: client.registrationStatus,
      stateRegistration: client.stateRegistration,
      cityRegistration: client.cityRegistration,
      foundedAt: client.foundedAt,
      establishedAt: client.establishedAt,
      closedAt: client.closedAt,
      closureReason: client.closureReason,
      isPep: client.isPep,
      isPepRelated: client.isPepRelated,
      isOfacListed: client.isOfacListed,
      hasRiskProfession: client.hasRiskProfession,
      hasRiskActivity: client.hasRiskActivity,
      hasRiskCity: client.hasRiskCity,
      riskRating: client.riskRating,
      revenueSituation: client.revenueSituation,
      economicGroupId: client.economicGroupId,
      legacySgsId: client.legacySgsId,
      legacyNfId: client.legacyNfId,
      assignedTo: client.assignedTo,
      teamId: client.teamId,
      regionId: client.regionId,
      cnpjStatus: client.cnpjStatus,
      cnpjValidatedAt: client.cnpjValidatedAt,
    };
  }
}
