import type { IrpfExtractionProps } from '../../domain/irpf-extraction.entity';
import type { IrpfExtractionStatus, IrpfConfidenceLevel, IrpfConflict } from '@nexus/types';

export class IrpfExtractionMapper {
  static toDomain(row: Record<string, unknown>): IrpfExtractionProps {
    return {
      id: row.id as string,
      clientId: row.clientId as string,
      authorizedPersonId: (row.authorizedPersonId as string) ?? null,
      cpf: row.cpf as string,
      exerciseYear: row.exerciseYear as number,
      calendarYear: row.calendarYear as number,
      fullName: (row.fullName as string) ?? null,
      birthDate: (row.birthDate as string) ?? null,
      occupation: (row.occupation as string) ?? null,
      occupationCode: (row.occupationCode as string) ?? null,
      nationality: (row.nationality as string) ?? null,
      naturality: (row.naturality as string) ?? null,
      phone: (row.phone as string) ?? null,
      email: (row.email as string) ?? null,
      addressStreet: (row.addressStreet as string) ?? null,
      addressNumber: (row.addressNumber as string) ?? null,
      addressComplement: (row.addressComplement as string) ?? null,
      addressNeighborhood: (row.addressNeighborhood as string) ?? null,
      addressCity: (row.addressCity as string) ?? null,
      addressState: (row.addressState as string) ?? null,
      addressZip: (row.addressZip as string) ?? null,
      spouseName: (row.spouseName as string) ?? null,
      spouseCpf: (row.spouseCpf as string) ?? null,
      declarationType: (row.declarationType as string) ?? null,
      taxationOption: (row.taxationOption as string) ?? null,
      receiptNumber: (row.receiptNumber as string) ?? null,
      deliveryTimestamp: row.deliveryTimestamp ? new Date(row.deliveryTimestamp as string) : null,
      totalTaxableIncome: (row.totalTaxableIncome as string) ?? null,
      totalExemptIncome: (row.totalExemptIncome as string) ?? null,
      totalExclusiveIncome: (row.totalExclusiveIncome as string) ?? null,
      totalDeductions: (row.totalDeductions as string) ?? null,
      taxableBase: (row.taxableBase as string) ?? null,
      taxDue: (row.taxDue as string) ?? null,
      taxPaid: (row.taxPaid as string) ?? null,
      taxRefund: (row.taxRefund as string) ?? null,
      taxBalance: (row.taxBalance as string) ?? null,
      totalAssetsCurrentYear: (row.totalAssetsCurrentYear as string) ?? null,
      totalAssetsPreviousYear: (row.totalAssetsPreviousYear as string) ?? null,
      totalDebtsCurrentYear: (row.totalDebtsCurrentYear as string) ?? null,
      totalDebtsPreviousYear: (row.totalDebtsPreviousYear as string) ?? null,
      dependents: row.dependents ?? null,
      taxableIncomeItems: row.taxableIncomeItems ?? null,
      exemptIncomeItems: row.exemptIncomeItems ?? null,
      exclusiveIncomeItems: row.exclusiveIncomeItems ?? null,
      payments: row.payments ?? null,
      assets: row.assets ?? null,
      debts: row.debts ?? null,
      extractionStatus: (row.extractionStatus as IrpfExtractionStatus) ?? 'pending',
      extractionConfidence: (row.extractionConfidence as IrpfConfidenceLevel) ?? null,
      ocrApplied: (row.ocrApplied as boolean) ?? false,
      needsReview: (row.needsReview as boolean) ?? false,
      conflicts: (row.conflicts as IrpfConflict[]) ?? null,
      extractionLog: row.extractionLog ?? null,
      createdAt: row.createdAt ? new Date(row.createdAt as string) : null,
      updatedAt: row.updatedAt ? new Date(row.updatedAt as string) : null,
    };
  }

  static toResponse(props: IrpfExtractionProps): Record<string, unknown> {
    return {
      id: props.id,
      clientId: props.clientId,
      authorizedPersonId: props.authorizedPersonId,
      cpf: props.cpf,
      exerciseYear: props.exerciseYear,
      calendarYear: props.calendarYear,
      fullName: props.fullName,
      declarationType: props.declarationType,
      taxationOption: props.taxationOption,
      receiptNumber: props.receiptNumber,
      deliveryTimestamp: props.deliveryTimestamp?.toISOString() ?? null,
      totalTaxableIncome: props.totalTaxableIncome,
      totalExemptIncome: props.totalExemptIncome,
      totalExclusiveIncome: props.totalExclusiveIncome,
      totalDeductions: props.totalDeductions,
      taxableBase: props.taxableBase,
      taxDue: props.taxDue,
      taxPaid: props.taxPaid,
      taxRefund: props.taxRefund,
      taxBalance: props.taxBalance,
      totalAssetsCurrentYear: props.totalAssetsCurrentYear,
      totalAssetsPreviousYear: props.totalAssetsPreviousYear,
      totalDebtsCurrentYear: props.totalDebtsCurrentYear,
      totalDebtsPreviousYear: props.totalDebtsPreviousYear,
      dependents: props.dependents,
      taxableIncomeItems: props.taxableIncomeItems,
      exemptIncomeItems: props.exemptIncomeItems,
      exclusiveIncomeItems: props.exclusiveIncomeItems,
      payments: props.payments,
      assets: props.assets,
      debts: props.debts,
      extractionStatus: props.extractionStatus,
      extractionConfidence: props.extractionConfidence,
      ocrApplied: props.ocrApplied,
      needsReview: props.needsReview,
      conflicts: props.conflicts,
      createdAt: props.createdAt?.toISOString() ?? null,
      updatedAt: props.updatedAt?.toISOString() ?? null,
    };
  }
}
