import type { Node, Edge } from '@xyflow/react';

const COL_WIDTH = 380;
const GROUP_HEIGHT_UNIT = 200;

// Groups (domains) — positioned in a 3-column grid
export const databaseNodes: Node[] = [
  // ─── GROUP: Core ───────────────────────────────────────
  {
    id: 'g-core',
    type: 'group',
    position: { x: 0, y: 0 },
    style: { width: COL_WIDTH, height: 220, backgroundColor: 'rgba(16, 185, 129, 0.04)', borderRadius: 12, border: '1px solid rgba(16,185,129,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-core-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-core',
    extent: 'parent',
    data: { tableName: '⬡ CORE', color: 'green' },
  },
  {
    id: 't-profiles',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-core',
    extent: 'parent',
    data: { tableName: 'profiles', columns: ['id (uuid)', 'role', 'full_name', 'avatar_url'], color: 'green' },
  },
  {
    id: 't-regions',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-core',
    extent: 'parent',
    data: { tableName: 'regions', columns: ['id', 'name', 'manager_id'], color: 'green' },
  },
  {
    id: 't-teams',
    type: 'tableNode',
    position: { x: 12, y: 150 },
    parentId: 'g-core',
    extent: 'parent',
    data: { tableName: 'teams', columns: ['id', 'name', 'region_id', 'supervisor_id'], color: 'green' },
  },
  {
    id: 't-audit',
    type: 'tableNode',
    position: { x: 202, y: 150 },
    parentId: 'g-core',
    extent: 'parent',
    data: { tableName: 'audit_logs', columns: ['id', 'actor_id', 'action', 'entity', 'payload'], color: 'green' },
  },

  // ─── GROUP: Commercial ────────────────────────────────
  {
    id: 'g-commercial',
    type: 'group',
    position: { x: COL_WIDTH + 40, y: 0 },
    style: { width: COL_WIDTH, height: GROUP_HEIGHT_UNIT * 2.2, backgroundColor: 'rgba(59, 130, 246, 0.04)', borderRadius: 12, border: '1px solid rgba(59,130,246,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-commercial-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-commercial',
    extent: 'parent',
    data: { tableName: '⬡ COMERCIAL', color: 'blue' },
  },
  {
    id: 't-clients',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-commercial',
    extent: 'parent',
    data: { tableName: 'clients', columns: ['id', 'cnpj/cpf', 'status (21)', 'segment_id', 'assigned_to'], color: 'blue' },
  },
  {
    id: 't-client-docs',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-commercial',
    extent: 'parent',
    data: { tableName: 'client_documents', columns: ['id', 'client_id', 'category', 'status'], color: 'blue' },
  },
  {
    id: 't-client-status',
    type: 'tableNode',
    position: { x: 12, y: 180 },
    parentId: 'g-commercial',
    extent: 'parent',
    data: { tableName: 'client_status_history', columns: ['id', 'client_id', 'from', 'to', 'actor_id'], color: 'blue' },
  },
  {
    id: 't-sales-goals',
    type: 'tableNode',
    position: { x: 202, y: 180 },
    parentId: 'g-commercial',
    extent: 'parent',
    data: { tableName: 'sales_goals', columns: ['id', 'level', 'target_id', 'amount', 'period'], color: 'blue' },
  },
  {
    id: 't-segments',
    type: 'tableNode',
    position: { x: 12, y: 300 },
    parentId: 'g-commercial',
    extent: 'parent',
    data: { tableName: 'segments', columns: ['id', 'name', 'code'], color: 'blue' },
  },
  {
    id: 't-credit-products',
    type: 'tableNode',
    position: { x: 202, y: 300 },
    parentId: 'g-commercial',
    extent: 'parent',
    data: { tableName: 'credit_products', columns: ['id', 'name', 'code', 'type'], color: 'blue' },
  },

  // ─── GROUP: Credit / Integrations ─────────────────────
  {
    id: 'g-credit',
    type: 'group',
    position: { x: (COL_WIDTH + 40) * 2, y: 0 },
    style: { width: COL_WIDTH, height: 220, backgroundColor: 'rgba(139, 92, 246, 0.04)', borderRadius: 12, border: '1px solid rgba(139,92,246,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-credit-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-credit',
    extent: 'parent',
    data: { tableName: '⬡ CRÉDITO / INTEGRAÇÕES', color: 'purple' },
  },
  {
    id: 't-vadu-company',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-credit',
    extent: 'parent',
    data: { tableName: 'vadu_company_results', columns: ['id', 'client_id', 'cnpj', 'result_json'], color: 'purple' },
  },
  {
    id: 't-vadu-person',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-credit',
    extent: 'parent',
    data: { tableName: 'vadu_person_results', columns: ['id', 'client_id', 'cpf', 'result_json'], color: 'purple' },
  },
  {
    id: 't-creditbox',
    type: 'tableNode',
    position: { x: 12, y: 150 },
    parentId: 'g-credit',
    extent: 'parent',
    data: { tableName: 'creditbox_reports', columns: ['id', 'client_id', 'report_json', 'queried_at'], color: 'purple' },
  },

  // ─── GROUP: Drawees ────────────────────────────────────
  {
    id: 'g-drawees',
    type: 'group',
    position: { x: 0, y: 260 },
    style: { width: COL_WIDTH, height: 220, backgroundColor: 'rgba(14, 165, 233, 0.04)', borderRadius: 12, border: '1px solid rgba(14,165,233,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-drawees-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-drawees',
    extent: 'parent',
    data: { tableName: '⬡ SACADOS', color: 'sky' },
  },
  {
    id: 't-drawees',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-drawees',
    extent: 'parent',
    data: { tableName: 'drawees', columns: ['id', 'cnpj/cpf', 'name', 'status', 'group_id'], color: 'sky' },
  },
  {
    id: 't-drawee-products',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-drawees',
    extent: 'parent',
    data: { tableName: 'drawee_enabled_products', columns: ['drawee_id', 'product_id', 'enabled_at'], color: 'sky' },
  },
  {
    id: 't-econ-groups',
    type: 'tableNode',
    position: { x: 12, y: 155 },
    parentId: 'g-drawees',
    extent: 'parent',
    data: { tableName: 'economic_groups', columns: ['id', 'name', 'lead_client_id'], color: 'sky' },
  },

  // ─── GROUP: Financial ──────────────────────────────────
  {
    id: 'g-financial',
    type: 'group',
    position: { x: COL_WIDTH + 40, y: 460 },
    style: { width: COL_WIDTH, height: 220, backgroundColor: 'rgba(20, 184, 166, 0.04)', borderRadius: 12, border: '1px solid rgba(20,184,166,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-financial-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-financial',
    extent: 'parent',
    data: { tableName: '⬡ FINANCEIRO', color: 'teal' },
  },
  {
    id: 't-fin-accounts',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-financial',
    extent: 'parent',
    data: { tableName: 'financial_accounts', columns: ['id', 'client_id', 'balance', 'type'], color: 'teal' },
  },
  {
    id: 't-fin-transactions',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-financial',
    extent: 'parent',
    data: { tableName: 'financial_transactions', columns: ['id', 'account_id', 'amount', 'type', 'event_type_id'], color: 'teal' },
  },
  {
    id: 't-fin-pendencies',
    type: 'tableNode',
    position: { x: 12, y: 155 },
    parentId: 'g-financial',
    extent: 'parent',
    data: { tableName: 'financial_pendencies', columns: ['id', 'account_id', 'amount', 'due_date'], color: 'teal' },
  },

  // ─── GROUP: Debentures ─────────────────────────────────
  {
    id: 'g-debentures',
    type: 'group',
    position: { x: (COL_WIDTH + 40) * 2, y: 260 },
    style: { width: COL_WIDTH, height: 230, backgroundColor: 'rgba(99, 102, 241, 0.04)', borderRadius: 12, border: '1px solid rgba(99,102,241,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-debentures-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-debentures',
    extent: 'parent',
    data: { tableName: '⬡ DEBÊNTURES', color: 'indigo' },
  },
  {
    id: 't-deb-issuers',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-debentures',
    extent: 'parent',
    data: { tableName: 'debenture_issuers', columns: ['id', 'name', 'cnpj'], color: 'indigo' },
  },
  {
    id: 't-deb-issuances',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-debentures',
    extent: 'parent',
    data: { tableName: 'debenture_issuances', columns: ['id', 'issuer_id', 'code', 'total_amount'], color: 'indigo' },
  },
  {
    id: 't-deb-subscriptions',
    type: 'tableNode',
    position: { x: 12, y: 155 },
    parentId: 'g-debentures',
    extent: 'parent',
    data: { tableName: 'debenture_subscriptions', columns: ['id', 'series_id', 'client_id', 'amount'], color: 'indigo' },
  },

  // ─── GROUP: People ─────────────────────────────────────
  {
    id: 'g-people',
    type: 'group',
    position: { x: 0, y: 520 },
    style: { width: COL_WIDTH, height: 240, backgroundColor: 'rgba(244, 63, 94, 0.04)', borderRadius: 12, border: '1px solid rgba(244,63,94,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-people-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-people',
    extent: 'parent',
    data: { tableName: '⬡ PESSOAS (RH/DP)', color: 'rose' },
  },
  {
    id: 't-collaborators',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-people',
    extent: 'parent',
    data: { tableName: 'collaborators', columns: ['id', 'profile_id', 'employment_type', 'department'], color: 'rose' },
  },
  {
    id: 't-clt-data',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-people',
    extent: 'parent',
    data: { tableName: 'collaborator_clt_data', columns: ['collaborator_id', 'ctps', 'base_salary', 'pis'], color: 'rose' },
  },
  {
    id: 't-reimbursements',
    type: 'tableNode',
    position: { x: 12, y: 165 },
    parentId: 'g-people',
    extent: 'parent',
    data: { tableName: 'reimbursements', columns: ['id', 'collaborator_id', 'amount', 'status'], color: 'rose' },
  },
  {
    id: 't-pj-invoices',
    type: 'tableNode',
    position: { x: 202, y: 165 },
    parentId: 'g-people',
    extent: 'parent',
    data: { tableName: 'pj_invoices', columns: ['id', 'collaborator_id', 'month', 'amount', 'status'], color: 'rose' },
  },

  // ─── GROUP: Learning ───────────────────────────────────
  {
    id: 'g-learning',
    type: 'group',
    position: { x: (COL_WIDTH + 40) * 2, y: 530 },
    style: { width: COL_WIDTH, height: 230, backgroundColor: 'rgba(168, 85, 247, 0.04)', borderRadius: 12, border: '1px solid rgba(168,85,247,0.2)' },
    data: { label: '' },
  },
  {
    id: 'g-learning-label',
    type: 'tableNode',
    position: { x: 12, y: 12 },
    parentId: 'g-learning',
    extent: 'parent',
    data: { tableName: '⬡ APRENDIZAGEM', color: 'purple' },
  },
  {
    id: 't-courses',
    type: 'tableNode',
    position: { x: 12, y: 60 },
    parentId: 'g-learning',
    extent: 'parent',
    data: { tableName: 'learning_courses', columns: ['id', 'title', 'category', 'status', 'mandatory'], color: 'purple' },
  },
  {
    id: 't-lessons',
    type: 'tableNode',
    position: { x: 202, y: 60 },
    parentId: 'g-learning',
    extent: 'parent',
    data: { tableName: 'learning_lessons', columns: ['id', 'module_id', 'title', 'youtube_url'], color: 'purple' },
  },
  {
    id: 't-enrollments',
    type: 'tableNode',
    position: { x: 12, y: 155 },
    parentId: 'g-learning',
    extent: 'parent',
    data: { tableName: 'learning_enrollments', columns: ['id', 'course_id', 'collaborator_id', 'status'], color: 'purple' },
  },
];

export const databaseEdges: Edge[] = [
  // profiles → clients (assigned_to)
  {
    id: 'e-profiles-clients',
    source: 't-profiles',
    target: 't-clients',
    label: 'assigned_to',
    style: { stroke: 'hsl(150, 25%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // clients → client_docs
  {
    id: 'e-clients-docs',
    source: 't-clients',
    target: 't-client-docs',
    label: 'client_id',
    style: { stroke: 'hsl(220, 60%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // clients → status history
  {
    id: 'e-clients-status',
    source: 't-clients',
    target: 't-client-status',
    label: 'client_id',
    style: { stroke: 'hsl(220, 60%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // clients → vadu
  {
    id: 'e-clients-vadu',
    source: 't-clients',
    target: 't-vadu-company',
    label: 'client_id',
    style: { stroke: 'hsl(270, 50%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // clients → creditbox
  {
    id: 'e-clients-creditbox',
    source: 't-clients',
    target: 't-creditbox',
    label: 'client_id',
    style: { stroke: 'hsl(270, 50%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // drawees → economic_groups
  {
    id: 'e-drawees-econ',
    source: 't-drawees',
    target: 't-econ-groups',
    label: 'group_id',
    style: { stroke: 'hsl(200, 60%, 60%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // financial_accounts → clients
  {
    id: 'e-finaccts-clients',
    source: 't-fin-accounts',
    target: 't-clients',
    label: 'client_id',
    style: { stroke: 'hsl(170, 50%, 55%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // transactions → accounts
  {
    id: 'e-transactions-accts',
    source: 't-fin-transactions',
    target: 't-fin-accounts',
    label: 'account_id',
    style: { stroke: 'hsl(170, 50%, 55%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // debenture subscriptions → clients
  {
    id: 'e-deb-sub-clients',
    source: 't-deb-subscriptions',
    target: 't-clients',
    label: 'client_id',
    style: { stroke: 'hsl(240, 50%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // collaborators → profiles
  {
    id: 'e-collab-profiles',
    source: 't-collaborators',
    target: 't-profiles',
    label: 'profile_id',
    style: { stroke: 'hsl(350, 60%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // enrollments → collaborators
  {
    id: 'e-enroll-collab',
    source: 't-enrollments',
    target: 't-collaborators',
    label: 'collaborator_id',
    style: { stroke: 'hsl(270, 50%, 65%)', strokeWidth: 1.5 },
    labelStyle: { fontSize: 9 },
  },
  // segments ← clients
  {
    id: 'e-clients-segment',
    source: 't-clients',
    target: 't-segments',
    label: 'segment_id',
    style: { stroke: 'hsl(220, 50%, 65%)', strokeWidth: 1, strokeDasharray: '4 3' },
    labelStyle: { fontSize: 9 },
  },
];
