import type { NotificationType } from '@nexus/types';

export const NOTIFICATION_TYPE_LABELS: Partial<Record<NotificationType, string>> = {
  document_rejected: 'Documento rejeitado',
  client_approved: 'Cliente aprovado',
  client_rejected: 'Cliente não aprovado',
  client_auto_rejected: 'Cliente não aprovado (automático)',
  client_reassigned_to_me: 'Cliente reassignado para você',
  client_reassigned_from_me: 'Cliente reassignado',
  goal_achieved: 'Meta atingida',
  client_inactive_7days: 'Cliente inativo há 7 dias',
  team_goal_achieved: 'Meta da equipe atingida',
  region_goal_achieved: 'Meta regional atingida',
  team_below_target: 'Equipe abaixo da meta',
  national_goal_achieved: 'Meta nacional atingida',
  large_operation_approved: 'Grande operação aprovada',
  region_below_target: 'Região abaixo da meta',
  new_client_in_queue: 'Novo cliente na fila',
  bureau_query_failed: 'Consulta bureau falhou',
  bureau_unavailable: 'Bureau indisponível',
  auto_reject_override_requested: 'Solicitação de override',
  new_client_compliance_queue: 'Novo cliente na fila de compliance',
  pep_match_found: 'PEP encontrado',
  sanction_match_found: 'Sanção encontrada',
  monitoring_alert: 'Alerta de monitoramento',
  coaf_report_due: 'Relatório COAF pendente',
  new_client_approval_queue: 'Novo cliente na fila de aprovação',
  report_ready_for_review: 'Relatório pronto para revisão',
  approval_sla_warning: 'Alerta de SLA de aprovação',
  homologation_complete: 'Homologação concluída',
  homologation_rejected: 'Homologação rejeitada',
  partner_docs_uploaded: 'Docs dos sócios enviados',
  divergence_detected: 'Divergência detectada',
  contract_signed: 'Contrato assinado',
  contract_generation_ready: 'Geração de contrato pronta',
  contract_review_requested: 'Revisão de contrato solicitada',
  extrajudicial_auto_generated: 'Extrajudicial gerada',
  litigation_update: 'Atualização contencioso',
  signature_completed: 'Assinatura concluída',
  regulation_review_requested: 'Revisão regulatória solicitada',
  client_entered_risk: 'Cliente entrou em risco',
  client_entered_recovery: 'Cliente em recuperação',
  client_entered_litigation: 'Cliente em contencioso',
  payment_received: 'Pagamento recebido',
  negotiation_deadline: 'Prazo de negociação',
  settlement_expired: 'Acordo expirado',
  reimbursement_approved: 'Reembolso aprovado',
  reimbursement_rejected: 'Reembolso recusado',
  reimbursement_pending_approval: 'Reembolso pendente de aprovação',
  reimbursement_pending_payment: 'Reembolso pendente de pagamento',
  pj_invoice_uploaded: 'NF PJ enviada',
  pj_invoice_overdue: 'NF PJ atrasada',
  review_cycle_open: 'Ciclo de avaliação aberto',
  onboarding_task_due: 'Tarefa de onboarding pendente',
  review_cycle_deadline: 'Prazo do ciclo de avaliação',
  turnover_alert: 'Alerta de turnover',
  system_error: 'Erro do sistema',
  integration_down: 'Integração indisponível',
  security_alert: 'Alerta de segurança',
  new_user_created: 'Novo usuário criado',
};

export const NOTIFICATION_TYPE_ICONS: Partial<Record<NotificationType, string>> = {
  document_rejected: 'FileX',
  client_approved: 'CheckCircle',
  client_rejected: 'XCircle',
  client_auto_rejected: 'Ban',
  goal_achieved: 'Target',
  new_client_in_queue: 'Inbox',
  bureau_query_failed: 'AlertTriangle',
  bureau_unavailable: 'WifiOff',
  reimbursement_approved: 'CheckCircle',
  reimbursement_rejected: 'XCircle',
  reimbursement_pending_approval: 'Clock',
  pj_invoice_uploaded: 'FileText',
  pj_invoice_overdue: 'AlertCircle',
  contract_signed: 'FileSignature',
  payment_received: 'DollarSign',
  system_error: 'AlertTriangle',
  integration_down: 'Plug',
  security_alert: 'ShieldAlert',
};

export function getNotificationTypeLabel(type: string): string {
  return NOTIFICATION_TYPE_LABELS[type as NotificationType] ?? type;
}

export function getNotificationTypeIcon(type: string): string {
  return NOTIFICATION_TYPE_ICONS[type as NotificationType] ?? 'Bell';
}
