import { TradeReceivableEntity, type TradeReceivableProps } from '../../domain/trade-receivable.entity';
import type { TradeReceivableStatus, EvaluationStatus } from '@nexus/types';
import type { tradeReceivables } from '../../../../database/schema';

type TradeReceivableRow = typeof tradeReceivables.$inferSelect;

export class TradeReceivableMapper {
  static toDomain(row: TradeReceivableRow): TradeReceivableEntity {
    const props: TradeReceivableProps = {
      id: row.id,
      clientId: row.clientId,
      draweeId: row.draweeId,
      cnabFileId: row.cnabFileId,
      documentNumber: row.documentNumber,
      ourNumber: row.ourNumber,
      documentType: row.documentType,
      speciesCode: row.speciesCode,
      issueDate: row.issueDate,
      dueDate: row.dueDate,
      faceValue: row.faceValue,
      interestPerDay: row.interestPerDay,
      discountValue: row.discountValue,
      discountDeadline: row.discountDeadline,
      penaltyValue: row.penaltyValue,
      iofValue: row.iofValue,
      acceptance: row.acceptance,
      instruction1: row.instruction1,
      instruction2: row.instruction2,
      draweeDocType: row.draweeDocType,
      draweeDoc: row.draweeDoc,
      draweeName: row.draweeName,
      draweeAddress: row.draweeAddress,
      draweeNeighborhood: row.draweeNeighborhood,
      draweeZip: row.draweeZip,
      draweeCity: row.draweeCity,
      draweeState: row.draweeState,
      draweeEmail: row.draweeEmail,
      bankCode: row.bankCode,
      branch: row.branch,
      portfolioCode: row.portfolioCode,
      status: (row.status ?? 'pending') as TradeReceivableStatus,
      operationId: row.operationId,
      evaluationStatus: (row.evaluationStatus ?? 'pending') as EvaluationStatus,
      rejectionReason: row.rejectionReason,
      portfolioPositionId: row.portfolioPositionId,
      cnabRecordSequence: row.cnabRecordSequence,
      rawLine: row.rawLine,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };
    return TradeReceivableEntity.reconstitute(props);
  }

  static toPersistence(entity: TradeReceivableEntity): Record<string, unknown> {
    return {
      clientId: entity.clientId,
      draweeId: entity.draweeId,
      cnabFileId: entity.cnabFileId,
      documentNumber: entity.documentNumber,
      ourNumber: entity.ourNumber,
      documentType: entity.documentType,
      speciesCode: entity.speciesCode,
      issueDate: entity.issueDate,
      dueDate: entity.dueDate,
      faceValue: entity.faceValue,
      interestPerDay: entity.interestPerDay,
      discountValue: entity.discountValue,
      discountDeadline: entity.discountDeadline,
      penaltyValue: entity.penaltyValue,
      iofValue: entity.iofValue,
      acceptance: entity.acceptance,
      instruction1: entity.instruction1,
      instruction2: entity.instruction2,
      draweeDocType: entity.draweeDocType,
      draweeDoc: entity.draweeDoc,
      draweeName: entity.draweeName,
      draweeAddress: entity.draweeAddress,
      draweeNeighborhood: entity.draweeNeighborhood,
      draweeZip: entity.draweeZip,
      draweeCity: entity.draweeCity,
      draweeState: entity.draweeState,
      draweeEmail: entity.draweeEmail,
      bankCode: entity.bankCode,
      branch: entity.branch,
      portfolioCode: entity.portfolioCode,
      status: entity.status,
      operationId: entity.operationId,
      evaluationStatus: entity.evaluationStatus,
      rejectionReason: entity.rejectionReason,
      portfolioPositionId: entity.portfolioPositionId,
      cnabRecordSequence: entity.cnabRecordSequence,
      rawLine: entity.rawLine,
    };
  }
}
