export type EmploymentType = 'clt' | 'pj';

export type BankAccountType = 'pf' | 'pj';

export interface Collaborator {
  id: string;
  profileId: string | null;
  isActive: boolean;
  registrationNumber: string | null;
  badgeNumber: string | null;
  employmentType: EmploymentType;
  isInternal: boolean;
  fullName: string;
  socialName: string | null;
  dateOfBirth: string | null;
  gender: string | null;
  maritalStatus: string | null;
  nationality: string;
  cpf: string | null;
  rg: string | null;
  rgIssuer: string | null;
  addressStreet: string | null;
  addressNumber: string | null;
  addressComplement: string | null;
  addressNeighborhood: string | null;
  addressCity: string | null;
  addressState: string | null;
  addressZip: string | null;
  phone: string | null;
  personalEmail: string | null;
  corporateEmail: string | null;
  extension: string | null;
  company: string;
  directorate: string | null;
  department: string | null;
  branch: string | null;
  managerId: string | null;
  jobTitle: string | null;
  roleCode: string | null;
  roleLevel: string | null;
  startDateOriginal: string | null;
  startDateCurrent: string | null;
  registrationDate: string | null;
  terminationDate: string | null;
  terminationReason: string | null;
  terminationYear: number | null;
  hasMedicalAssistance: boolean;
  plrEligible: boolean;
  thirteenthPj: boolean;
  guaranteedBonus: number | null;
  commissionPct: number | null;
  bankName: string | null;
  bankBranch: string | null;
  bankAccount: string | null;
  bankAccountType: BankAccountType | null;
  currentSalary: number | null;
  lastMovementDate: string | null;
  lastMovementType: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}
