import { pgTable, uuid, text, boolean, integer, numeric, date, timestamp, index } from 'drizzle-orm/pg-core';
import { profiles } from './profiles';

export const collaborators = pgTable('collaborators', {
  id: uuid('id').primaryKey().defaultRandom(),
  profileId: uuid('profile_id').unique().references(() => profiles.id),
  isActive: boolean('is_active').notNull().default(true),
  registrationNumber: text('registration_number').unique(),
  badgeNumber: text('badge_number'),
  employmentType: text('employment_type').notNull(),
  isInternal: boolean('is_internal').default(true),
  fullName: text('full_name').notNull(),
  socialName: text('social_name'),
  dateOfBirth: date('date_of_birth'),
  gender: text('gender'),
  maritalStatus: text('marital_status'),
  nationality: text('nationality').default('Brasileira'),
  cpf: text('cpf').unique(),
  rg: text('rg'),
  rgIssuer: text('rg_issuer'),
  voterRegistration: text('voter_registration'),
  voterZone: text('voter_zone'),
  voterSection: text('voter_section'),
  militaryCert: text('military_cert'),
  addressStreet: text('address_street'),
  addressNumber: text('address_number'),
  addressComplement: text('address_complement'),
  addressNeighborhood: text('address_neighborhood'),
  addressCity: text('address_city'),
  addressState: text('address_state'),
  addressZip: text('address_zip'),
  phone: text('phone'),
  personalEmail: text('personal_email'),
  corporateEmail: text('corporate_email'),
  extension: text('extension'),
  company: text('company').default('Sarfaty'),
  directorate: text('directorate'),
  department: text('department'),
  branch: text('branch'),
  managerId: uuid('manager_id').references((): any => collaborators.id),
  jobTitle: text('job_title'),
  roleCode: text('role_code'),
  roleLevel: text('role_level'),
  startDateOriginal: date('start_date_original'),
  startDateCurrent: date('start_date_current'),
  registrationDate: date('registration_date'),
  terminationDate: date('termination_date'),
  terminationReason: text('termination_reason'),
  terminationYear: integer('termination_year'),
  hasMedicalAssistance: boolean('has_medical_assistance').default(true),
  medicalPlanNotes: text('medical_plan_notes'),
  plrEligible: boolean('plr_eligible').default(false),
  thirteenthPj: boolean('thirteenth_pj').default(false),
  guaranteedBonus: numeric('guaranteed_bonus', { precision: 15, scale: 2 }),
  commissionPct: numeric('commission_pct', { precision: 5, scale: 2 }),
  bankName: text('bank_name'),
  bankBranch: text('bank_branch'),
  bankAccount: text('bank_account'),
  bankAccountType: text('bank_account_type'),
  currentSalary: numeric('current_salary', { precision: 15, scale: 2 }),
  lastMovementDate: date('last_movement_date'),
  lastMovementType: text('last_movement_type'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => ({
  activeIdx: index('idx_collab_active').on(table.isActive),
  typeIdx: index('idx_collab_type').on(table.employmentType),
  managerIdx: index('idx_collab_manager').on(table.managerId),
  departmentIdx: index('idx_collab_department').on(table.department),
  directorateIdx: index('idx_collab_directorate').on(table.directorate),
  cpfIdx: index('idx_collab_cpf').on(table.cpf),
  profileIdx: index('idx_collab_profile').on(table.profileId),
}));
